name: HACS Action

on:
  push:
    branches:
      - main
  release:
    types: [published]
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  validate:
    runs-on: 'ubuntu-latest'
    steps:
      - name: HACS Action
        uses: 'hacs/action@main'
        with:
          category: 'plugin'
